language: objective-c

osx_image: xcode11.5
os: osx
env:
  jobs:
    - TEST_SDK=iphonesimulator10.15.4 OS=10.15.4 NAME='iPhone 11'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project CircularTimer.xcodeproj -scheme CircularTimer -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES