osx_image: xcode11.5
os: osx
language: swift

script: xcodebuild clean test -project CircularTimer.xcodeproj -scheme "CircularTimer" -destination "name=iPhone 11,OS=13.5" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f reports/cobertura.xml -X coveragepy -X gcov -X xcode