language: objective-c

osx_image: xcode11.5
env:
  matrix:
    - TEST_SDK=iphonesimulator12.1 OS=12.1 NAME='iPhone 11'

script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project CircularTimer.xcodeproj -scheme CircularTimer -sdk $TEST_SDK -destination "platform=iOS Simulator,OS=$OS,name=$NAME" ONLY_ACTIVE_ARCH=YES
